AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create WordPress configuration parameters in AWS Secrets Manager.

Resources:

  DBUserParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /AMATI/Wordpress/DBUser
      Description: Wordpress Database User
      Type: String
      Value: atiwordpressuser

  DBNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /AMATI/Wordpress/DBName
      Description: Wordpress Database Name
      Type: String
      Value: atiwordpressdb

  DBEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /AMATI/Wordpress/DBEndpoint
      Description: Endpoint for the Wordpress Database
      Type: String
      Value: rds_endpoint

  EFSFSIDParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /AMATI/Wordpress/EFSFSID
      Description: ID for the Wordpress FileSystem
      Type: String
      Value: fs_id






Outputs:
  DBUserParameterName:
    Description: "The name of the SSM Parameter for DB User"
    Value: !Ref DBUserParameter

  DBNameParameterName:
    Description: "The name of the SSM Parameter for DB Name"
    Value: !Ref DBNameParameter

  DBEndpointParameterName:
    Description: "The name of the SSM Parameter for DB Endpoint"
    Value: !Ref DBEndpointParameter

  EFSFSIDParameterName:
    Description: "The name of the SSM Parameter for EFS FS ID"
    Value: !Ref EFSFSIDParameter
