AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketName:
    Type: String
    Description: 'The name of the S3 bucket to be created'

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private

  EC2InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Principal: 
              Service: 
                - 'ec2.amazonaws.com'
            Action: 
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'S3PutObjectPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 's3:PutObject'
                Resource: !Sub 'arn:aws:s3:::${BucketName}/*'

  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - Ref: 'EC2InstanceRole'


  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId: 'ami-00beae93a2d981137'
      SecurityGroupIds: [!Ref MyEC2SecurityGroup]
      UserData: 
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            sudo yum update -y
            sudo yum install -y python3
            pip3 --version
            curl https://bootstrap.pypa.io/get-pip.py | sudo python3
            pip3 --version
            mkdir python
            cd python
            pip install openai -t .
            cd ..
            zip -r openai-lambda-package.zip python
            aws s3 cp openai-lambda-package.zip s3://${BucketName}/

  MyEC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable SSH access'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'

Outputs:
  S3BucketName:
    Description: 'Name of the newly created S3 bucket'
    Value: !Ref BucketName
  InstanceId:
    Description: 'InstanceId of the newly created EC2 instance'
    Value: !Ref MyEC2Instance
  AZ:
    Description: 'Availability Zone of the newly created EC2 instance'
    Value: !GetAtt MyEC2Instance.AvailabilityZone
  PublicDNS:
    Description: 'Public DNS of the newly created EC2 instance'
    Value: !GetAtt MyEC2Instance.PublicDnsName
