AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an IAM role for meeting summarization

Resources:
  SummarizeMeetingRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: 'summarize-meeting-role'
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Principal: 
              Service: 
                - 'lambda.amazonaws.com'
            Action: 
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonTranscribeFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchFullAccess'
      Tags:
        - Key: 'app'
          Value: 'meeting-summarizer'
        - Key: 'name'
          Value: 'summarize-meeting-role'

Outputs:
  RoleName:
    Description: 'Name of the IAM role created for meeting summarization'
    Value: !Ref SummarizeMeetingRole
  RoleArn:
    Description: 'ARN of the IAM role created for meeting summarization'
    Value: !GetAtt SummarizeMeetingRole.Arn
