AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MeetingSummarizerFunctionArn:
    Description: ARN of the Lambda function that summarizes meetings
    Type: String

Resources:
  RecordingS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'recordings-summarizer-bucket-4${AWS::AccountId}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .mp3
            Function: !Ref MeetingSummarizerFunctionArn

Outputs:
  BucketName:
    Value: !Ref RecordingS3Bucket
    Description: Name of the sample Amazon S3 bucket with a notification configuration.

